version: '3.8'

services:
  birthdaygram_db:
    image: postgres:16-bookworm
    restart: always
    volumes:
      - birthdaygram_database:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      - TZ=Europe/Moscow
  birthdaygram_bot:
    build: ./
    restart: always
    volumes:
      - ./logs/:/app/logs/
    depends_on:
      - birthdaygram_db
    env_file:
      - ./.env
    environment:
      - TZ=Europe/Moscow

volumes:
  birthdaygram_database:
